# Name of your application
service: mihaela_sava_website

# Name of the container image
image: mihaelasava/mihaela_sava_website

# Servers
servers:
  web:
    - 164.92.244.56

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: mihaela-sava.com

# Docker registry (Docker Hub in this example)
registry:
  server: https://index.docker.io/v1/
  username: mihaelasava
  password:
    - KAMAL_REGISTRY_PASSWORD

# ENV variables (Rails credentials etc.)
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_ENV: production

# Persistent volume for uploads (ActiveStorage, SQLite, etc.)
volumes:
  - "mihaela_sava_website_storage:/rails/storage"

# Assets bridge for smooth version updates
asset_path: /rails/public/assets

# Builder config
builder:
  arch: amd64
  args:
    RUBY_VERSION: ruby-3.3.6

# SSH user
ssh:
  user: mihaela-deployer

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
