# Name of your application
service: mihaela_sava_website

# Name of the container image
image: mihaelaandreeasava/mihaela_sava_website

# Servers
servers:
  web:
    - 164.92.244.56

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  hosts:
    - mihaela-sava.com
    - www.mihaela-sava.com

# Docker registry (Docker Hub)
registry:
  username: mihaelaandreeasava
  password:
    - KAMAL_REGISTRY_PASSWORD

# ENV variables
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true

# Persistent storage
volumes:
  - "mihaela_sava_website_storage:/rails/storage"

# Assets bridge
asset_path: /rails/public/assets

# Builder
builder:
  arch: amd64
  args:
    RUBY_VERSION: 3.3.6

# SSH
ssh:
  user: mihaela-deployer
  keys:
    - ~/.ssh/id_ed25519_personal

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
